fix(compile): reduce `web` image size; correctly set `emscripten` version

diff --git a/compile-godot-export-template/web/Dockerfile b/compile-godot-export-template/web/Dockerfile
--- a/compile-godot-export-template/web/Dockerfile
+++ b/compile-godot-export-template/web/Dockerfile
@@ -1,10 +1,10 @@
 # syntax=docker/dockerfile:1
 
 # ---------------------------------------------------------------------------- #
-#                              Image: Setup - Base                             #
+#                               Image: Setup - OS                              #
 # ---------------------------------------------------------------------------- #
 
-FROM ubuntu:24.04 AS img-setup-base
+FROM ubuntu:24.04 AS img-setup-os
 
 # ------------------------- Update: Package registry ------------------------- #
 
@@ -26,16 +26,13 @@ RUN \
     apt-get install -y --no-install-recommends \
     ca-certificates \
     pkg-config \
-    python3.12 \
-    # Install 'emscripten' dependencies
-    lbzip2 \
-    xz-utils
+    python3.12
 
 # ---------------------------------------------------------------------------- #
 #                             Image: Setup - Python                            #
 # ---------------------------------------------------------------------------- #
 
-FROM img-setup-base AS img-setup-python
+FROM img-setup-os AS img-setup-python
 
 # --------------------- Install: Python and Python 'venv' -------------------- #
 
@@ -45,30 +42,12 @@ RUN apt-get install -y --no-install-recommends \
     # Set up the virtual environment
     python3.12 -m venv "/venv"
 
-# ---------------------------------------------------------------------------- #
-#                           Image: Setup - Emscripten                          #
-# ---------------------------------------------------------------------------- #
-
-FROM img-setup-base AS img-setup-emscripten
-
-# --------------------- Install: Emscripten dependencies --------------------- #
-
-RUN apt-get install -y --no-install-recommends \
-    git
-
-# ---------------------- Download: Emscripten repository --------------------- #
-
-RUN git clone \
-    --no-tags \
-    --depth=1 \
-    https://github.com/emscripten-core/emsdk.git \
-    /emsdk
 
 # ---------------------------------------------------------------------------- #
-#                             Image: Setup - Final                             #
+#                              Image: Setup - Base                             #
 # ---------------------------------------------------------------------------- #
 
-FROM img-setup-base
+FROM img-setup-os AS img-setup-base
 
 # ------------------------------ Install: Python ----------------------------- #
 
@@ -78,29 +57,58 @@ ENV \
     PATH="/opt/python3/bin:$PATH" \
     VIRTUAL_ENV="/opt/python3"
 
-# ---------------------------- Install: Emscripten --------------------------- #
+# ---------------------------------------------------------------------------- #
+#                           Image: Setup - Emscripten                          #
+# ---------------------------------------------------------------------------- #
 
-COPY --from=img-setup-emscripten "/emsdk" "/opt/emsdk"
+FROM img-setup-base AS img-setup-emscripten
 
 # NOTE: See https://emscripten.org/docs/getting_started/downloads.html for the
 # latest installation instructions.
 
 ARG EMSCRIPTEN_SDK_VERSION=latest
 
-RUN \
-    /opt/emsdk/emsdk install "$EMSCRIPTEN_SDK_VERSION" && \
-    /opt/emsdk/emsdk activate "$EMSCRIPTEN_SDK_VERSION" && \
-    # Clean up installation
-    rm -fr /opt/emsdk/upstream/emscripten/tests && \
-    apt-get install -y --no-install-recommends binutils && \
-    (find /opt/emsdk/upstream/bin -type f -exec strip -s {} + || :) && \
-    apt-get remove -y --purge binutils
+# --------------------------- Install: Dependencies -------------------------- #
 
-ENV PATH="/opt/emsdk/upstream/emscripten:/opt/emsdk/upstream/bin:$PATH"
+RUN apt-get install -y --no-install-recommends \
+    git \
+    lbzip2 \
+    xz-utils
+
+# ---------------------- Download: Emscripten repository --------------------- #
+
+RUN git clone \
+    --no-tags \
+    --depth=1 \
+    $([ $EMSCRIPTEN_SDK_VERSION != latest ] && echo -b $EMSCRIPTEN_SDK_VERSION) \
+    https://github.com/emscripten-core/emsdk.git \
+    /emsdk
+
+# ---------------------------- Install: Emscripten --------------------------- #
+
+RUN \
+    /emsdk/emsdk install "$EMSCRIPTEN_SDK_VERSION" && \
+    /emsdk/emsdk activate "$EMSCRIPTEN_SDK_VERSION" && \
+    # Clean up installation
+    rm -fr /emsdk/upstream/emscripten/tests && \
+    apt-get install -y --no-install-recommends binutils && \
+    (find /emsdk/upstream/bin -type f -exec strip -s {} + || :)
+
+# ---------------------------------------------------------------------------- #
+#                             Image: Setup - Final                             #
+# ---------------------------------------------------------------------------- #
+
+FROM img-setup-base
 
 # ----------------------------- Clean: Apt cache ----------------------------- #
 
 RUN apt-get clean
+
+# ---------------------------- Install: Emscripten --------------------------- #
+
+COPY --from=img-setup-emscripten "/emsdk" "/opt/emsdk"
+
+ENV PATH="/opt/emsdk/upstream/emscripten:/opt/emsdk/upstream/bin:$PATH"
 
 # ------------------------------ Install: SCons ------------------------------ #
 
@@ -112,4 +120,4 @@ RUN python3.12 -m pip install \
 # Update 'SCONSFLAGS' so that consumers don't need to know the details of
 # Web-related settings.
 
-ENV SCONSFLAGS="platform=web javascript_eval=no dlink_enabled=no"
+ENV SCONSFLAGS="platform=web"
