refactor(export): modify action to use new `export_presets.cfg` action

diff --git a/export-godot-project-preset/action.yaml b/export-godot-project-preset/action.yaml
--- a/export-godot-project-preset/action.yaml
+++ b/export-godot-project-preset/action.yaml
@@ -153,46 +153,28 @@ runs:
         echo "Copied Godot export template to target path: $TARGET"
         echo "path=${TARGET#${{ github.workspace }}/}" >> $GITHUB_OUTPUT
 
-    - name: Checkout out 'godot-infra' repository
-      uses: actions/checkout@v4
-      with:
-        path: godot-infra
-        ref: main
-        repository: coffeebeats/godot-infra
-        submodules: false
-
     - name: Set path to export template in 'export_presets.cfg'
-      shell: bash
-      run: >-
-        ${{ steps.editor.outputs.path }}/bin/godot
-        --path $GITHUB_WORKSPACE/${{ steps.project.outputs.dir }}
-        --headless
-        --quit
-        -s $GITHUB_WORKSPACE/godot-infra/export-godot-project-preset/set-export-template-path.gd -- \
-        set \
-          ${{ inputs.preset-name }} \
-          "options.custom_template/$([[ "${{ inputs.profile }}" == "release" ]] && echo "release" || echo "debug")" \
-          "/github/workspace/${{ steps.export-template.outputs.path }}"
+      uses: coffeebeats/godot-infra/inspect-godot-export-presets@main
+      with:
+        operation: "set"
+        preset: "${{ inputs.preset-name }}"
+        key: "options.custom_template/$([[ ${{ inputs.profile }} == release ]] && echo release || echo debug)"
+        value: "/github/workspace/${{ steps.export-template.outputs.path }}"
 
-        echo "Set path to export template for preset '${{ inputs.preset-name }}': $TEMPLATE_PATH"
+    # ---------------------- Configure export properties --------------------- #
 
-    - name: Get the platform of the specified preset
-      id: preset
+    - name: Get the configured preset platform
+      uses: coffeebeats/godot-infra/inspect-godot-export-presets@main
+      id: preset-platform
+      with:
+        preset: "${{ inputs.preset-name }}"
+        key: "platform"
+
+    - name: Translate the preset platform
+      id: platform
       shell: bash
       run: |-
-        PLATFORM=$(
-          ${{ steps.editor.outputs.path }}/bin/godot \
-          --path $GITHUB_WORKSPACE/${{ steps.project.outputs.dir }} \
-          --headless \
-          --quit \
-          -s $GITHUB_WORKSPACE/godot-infra/export-godot-project-preset/export-preset.gd -- \
-          get \
-            ${{ inputs.preset-name }} \
-            platform \
-          | tail -n 1
-        )
-
-        case "$PLATFORM" in
+        case "${{ steps.preset-platform.outputs.value }}" in
           "Windows Desktop" ) PLATFORM="windows" ;;
           "macOS" ) PLATFORM="macos" ;;
           "Linux/X11" ) PLATFORM="linux" ;;
@@ -202,8 +184,30 @@ runs:
             exit 1
             ;;
 
-        echo "platform=$PLATFORM" >> $GITHUB_OUTPUT
+        echo "value=$PLATFORM" >> $GITHUB_OUTPUT
         echo "Determined platform for preset '${{ inputs.preset-name }}': $PLATFORM"
+
+    - name: Get the configured preset export path
+      uses: coffeebeats/godot-infra/inspect-godot-export-presets@main
+      id: preset-export-path
+      with:
+        preset: "${{ inputs.preset-name }}"
+        key: "export_path"
+
+    - name: Determine preset output path for action
+      id: export-path
+      shell: bash
+      run: |-
+        EXPORT_PATH=$(echo ${{ steps.preset-export-path.outputs.value }} | xargs realpath -m)
+        EXPORT_PATH="${EXPORT_PATH#${{ steps.project.outputs.dir }}/}"
+
+        if [[ "$EXPORT_PATH" == "/"* ]] || [[ "$EXPORT_PATH" == ".."* ]]; then
+          echo "Invalid 'export_path' property; expected project subpath: $EXPORT_PATH"
+          exit 1
+        fi
+
+        echo "path=./dist/$EXPORT_PATH" >> $GITHUB_OUTPUT
+        echo "Determined output path for preset '${{ inputs.preset-name }}': ./dist/$EXPORT_PATH"
 
     # ----------------------- Export the project preset ---------------------- #
 
@@ -217,33 +221,8 @@ runs:
 
         mkdir $GITHUB_WORKSPACE/dist
 
-    - name: Get the output path for the preset
-      id: preset-artifact
-      shell: bash
-      run: |-
-        EXPORT_PATH=$(
-          ${{ steps.editor.outputs.path }}/bin/godot \
-          --path $GITHUB_WORKSPACE/${{ steps.project.outputs.dir }} \
-          --headless \
-          --quit \
-          -s $GITHUB_WORKSPACE/godot-infra/export-godot-project-preset/export-preset.gd -- \
-          get ${{ inputs.preset-name }} export_path \
-          | tail -n 1 \
-          | xargs realpath -m
-        )
-
-        EXPORT_PATH="${EXPORT_PATH#${{ steps.project.outputs.dir }}/}"
-
-        if [[ "$EXPORT_PATH" == "/"* ]] || [[ "$EXPORT_PATH" == ".."* ]]; then
-          echo "Invalid 'export_path' property; expected project subpath: $EXPORT_PATH"
-          exit 1
-        fi
-
-        echo "path=./dist/$EXPORT_PATH" >> $GITHUB_OUTPUT
-        echo "Determined output path for preset '${{ inputs.preset-name }}': ./dist/$EXPORT_PATH"
-
     - name: Export the Godot project preset (MacOS)
-      if: steps.preset.outputs.platform == 'macos'
+      if: steps.platform.outputs.value == 'macos'
       uses: "coffeebeats/godot-infra/export-godot-project-preset/macos@main"
       with:
         pck-only: ${{ inputs.pck-only }}
@@ -252,7 +231,7 @@ runs:
 
         godot-editor-path: ${{ steps.editor.outputs.path }}/bin/godot
         godot-export-template-path: ${{ steps.export-template.outputs.path }}
-        preset-output-path: ${{ steps.preset-artifact.outputs.path }}
+        preset-output-path: ${{ steps.export-path.outputs.path }}
         project-path: ${{ steps.project.outputs.dir }}
 
         # Encryption secrets
@@ -269,7 +248,7 @@ runs:
         notarization-apple-id-password: ${{ inputs.notarization-apple-id-password }}
 
     - name: Export the Godot project preset (Windows)
-      if: steps.preset.outputs.platform == 'windows'
+      if: steps.platform.outputs.value == 'windows'
       uses: "coffeebeats/godot-infra/export-godot-project-preset/windows@main"
       with:
         pck-only: ${{ inputs.pck-only }}
@@ -278,7 +257,7 @@ runs:
 
         godot-editor-path: ${{ steps.editor.outputs.path }}/bin/godot
         godot-export-template-path: ${{ steps.export-template.outputs.path }}
-        preset-output-path: ${{ steps.preset-artifact.outputs.path }}
+        preset-output-path: ${{ steps.export-path.outputs.path }}
         project-path: ${{ steps.project.outputs.dir }}
 
         # Encryption secrets
@@ -304,7 +283,7 @@ runs:
       id: artifact
       shell: bash
       run: |
-        ARTIFACT_PATH="${{ github.workspace }}/${{ steps.preset-artifact.outputs.path }}"
+        ARTIFACT_PATH="${{ github.workspace }}/${{ steps.export-path.outputs.path }}"
 
         if [[ -d "$ARTIFACT_PATH" ]]; then
           WRAPPER_DIR="${{ runner.temp }}/dist"
