fix(compile): add `ANGLE` support on `macos`

diff --git a/compile-godot-export-template/macos/Dockerfile b/compile-godot-export-template/macos/Dockerfile
--- a/compile-godot-export-template/macos/Dockerfile
+++ b/compile-godot-export-template/macos/Dockerfile
@@ -132,6 +132,36 @@ RUN test "$OSXCROSS_SDK" = "$(ls /osxcross/bin | \grep 'darwin' | head -1 | cut 
     (echo "Missing OSXCross tools for OSXCross SDK: $OSXCROSS_SDK" && exit 1)
 
 # ---------------------------------------------------------------------------- #
+#                         Image: Setup - ANGLE support                         #
+# ---------------------------------------------------------------------------- #
+
+FROM img-setup-base AS img-setup-angle
+
+# -------------------------- Install: ANGLE library -------------------------- #
+
+# NOTE: Cross-compiling ANGLE for 'macos' requires building Apple 'clang'. This
+# is an expensive operation, so unless demonstrated to be required, just use the
+# prebuilt libraries.
+
+ARG GODOT_ANGLE_STATIC_VERSION
+RUN test -n "$GODOT_ANGLE_STATIC_VERSION" || (echo "Missing build argument: 'GODOT_ANGLE_STATIC_VERSION'" && exit 1)
+
+ENV GODOT_ANGLE_STATIC_BASE_URL="https://github.com/godotengine/godot-angle-static/releases/download/"
+
+RUN \
+    # Install installation dependencies
+    apt-get install -y --no-install-recommends \
+    jq \
+    unzip && \
+    # Download prebuilt 'arm64' and 'x86_64' ANGLE libraries
+    mkdir /angle && \
+    GODOT_ANGLE_STATIC_BASE_URL="https://github.com/godotengine/godot-angle-static/releases/download/$(printf "${GODOT_ANGLE_STATIC_VERSION}" | jq -sRr '@uri')"; \
+    curl -L -o macos_arm64.zip "$GODOT_ANGLE_STATIC_BASE_URL/godot-angle-static-arm64-macos-release.zip" && \
+    curl -L -o macos_x86_64.zip "$GODOT_ANGLE_STATIC_BASE_URL/godot-angle-static-x86_64-macos-release.zip" && \
+    unzip -o -d /angle macos_arm64.zip && rm -f macos_arm64.zip && \
+    unzip -o -d /angle macos_x86_64.zip && rm -f macos_x86_64.zip
+
+# ---------------------------------------------------------------------------- #
 #                             Image: Setup - Final                             #
 # ---------------------------------------------------------------------------- #
 
@@ -156,7 +186,6 @@ COPY \
     --from=img-setup-osxcross \
     "/osxcross" "/usr/local/lib/osxcross/target"
 
-
 # The 'osxcross/build_compiler_rt.sh' script installs libraries into these directories.
 ARG LLVM_VERSION
 COPY \
@@ -175,7 +204,7 @@ ENV \
     # the target directory for the darwin toolchains must be `$OSXCROSS_ROOT/target/...`.
     # See https://github.com/godotengine/godot/blob/c3ed7af12347aa04a3d3bb91bc726170e894758e/platform/macos/detect.py#L136-L140.
     PATH="/usr/local/lib/osxcross/target/bin:$PATH" \
-    LD_LIBRARY_PATH="/usr/local/lib/osxcross/target/lib:$LD_LIBRARY_PATH"
+    LD_LIBRARY_PATH="/usr/local/lib/osxcross/target/lib"
 
 # Fixes a linker error (see https://ttys3.dev/post/rust-cross-compile-mac-osx-target-under-linux/):
 # "x86_64-apple-darwin*-ld: error while loading shared libraries:
@@ -192,6 +221,10 @@ ENV VULKAN_SDK_ROOT="/usr/local/lib/vulkan-sdk"
 
 COPY --from=vulkan . "$VULKAN_SDK_ROOT"
 
+# -------------------------- Install: ANGLE support -------------------------- #
+
+COPY --from=img-setup-angle "/angle" "/opt/angle"
+
 # ------------------------------ Install: SCons ------------------------------ #
 
 RUN python3.12 -m pip install \
@@ -203,9 +236,10 @@ RUN python3.12 -m pip install \
 # related settings.
 
 ENV SCONSFLAGS="platform=macos osxcross_sdk=$OSXCROSS_SDK"
-ENV SCONSFLAGS="use_volk=no vulkan_sdk_path=$VULKAN_SDK_ROOT/macOS/lib/MoltenVK.xcframework $SCONSFLAGS"
+ENV SCONSFLAGS="$SCONSFLAGS use_volk=no vulkan_sdk_path=$VULKAN_SDK_ROOT/macOS/lib/MoltenVK.xcframework"
+ENV SCONSFLAGS="$SCONSFLAGS angle_libs=/opt/angle"
 
 # NOTE: As of Godot 4.0.3, the 'SCons' configuration does not correctly
 # detect clang usage via 'OSXCross'. Add in the missing compiler flags and
 # "common warnings" here (see https://github.com/godotengine/godot/blob/2267646bf4c29acf1342951d8726626817c742bd/SConstruct#L727-L730).
-ENV SCONSFLAGS="CC=clang CXX=clang ccflags='-Wno-ordered-compare-function-pointers' $SCONSFLAGS"
+ENV SCONSFLAGS="$SCONSFLAGS CC=clang CXX=clang ccflags='-Wno-ordered-compare-function-pointers'"
