fix(ci): block commits in `commit-changes` when target branch is missing (#261)

diff --git a/commit-changes/action.yaml b/commit-changes/action.yaml
--- a/commit-changes/action.yaml
+++ b/commit-changes/action.yaml
@@ -31,6 +31,11 @@ runs:
       working-directory: ${{ inputs.working-directory }}
       run: |-
         TARGET_BRANCH=$([[ ! -z "${{ inputs.target-branch }}" ]] && echo "${{ inputs.target-branch }}" || git branch --show-current)
+        if [[ -z "$TARGET_BRANCH" ]]; then
+          echo "Could not determine target branch; exiting."
+          exit 1
+        fi
+
         REMOTE_BRANCHES="$(git ls-remote --heads origin $TARGET_BRANCH)"
 
         TARGET_BRANCH_EXISTS="$([[ ! -z "$REMOTE_BRANCHES" ]] && echo true || echo false)"
