refactor(ci): replace compile/export workflows with actions

diff --git a/compile-godot-export-template/action.yml b/compile-godot-export-template/action.yml
--- a/compile-godot-export-template/action.yml
+++ b/compile-godot-export-template/action.yml
@@ -2,9 +2,15 @@ name: "🏗️ Compile: Godot export template"
 description: "Compiles a Godot export template for the specified platform."
 
 inputs:
-  godot-src-path:
-    description: "A path to the Godot source code."
+  godot-src-rev:
+    type: string
+    description: "The revision/tag name in the 'godot-src-repository' to check out."
     required: true
+  godot-src-repository:
+    type: string
+    description: "The name of a repository containing the Godot source code."
+    required: false
+    default: godotengine/godot
 
   arch:
     description: "The target architecture of the export template."
@@ -46,6 +52,34 @@ outputs:
 
 runs:
   using: composite
+
+  # -------------------- Vendor the Godot source code -------------------- #
+
+  - uses: coffeebeats/godot-infra/.github/actions/install-godot-source@v0
+    id: godot
+    with:
+      dst-path: ${{ github.workspace }}/godot
+      godot-src-rev: ${{ inputs.godot-src-rev }}
+      godot-src-repository: ${{ inputs.godot-src-repository }}
+
+  - name: Parse Godot source code version
+    uses: "coffeebeats/godot-infra/.github/actions/parse-godot-version@v0"
+    id: godot-version
+    with:
+      versionpy-path: ${{ github.workspace }}/godot/version.py
+
+  - name: Validate Godot source code version
+    shell: bash
+    env:
+      # TODO: If Godot ever releases more than '9' patch versions this will
+      # break. That's never happened before, so ignore for now.
+      GODOT_VERSION_MIN: 4.2.2
+    run: |
+      VERSION_ACTUAL="${{ steps.godot-version.outputs.major-minor-patch }}"
+      if [[ "$VERSION_ACTUAL" < "${{ env.GODOT_VERSION_MIN }}"* ]]; then
+        echo "Supplied editor '$VERSION_ACTUAL' less than required minimum: ${{ env.GODOT_VERSION_MIN }}"
+        exit 1
+      fi
 
   steps:
     - name: Copy the Godot source code to the expected location
@@ -189,3 +223,13 @@ runs:
         DOUBLE=$([[ "${{ inputs.use-double-precision }}" == "true" ]] && echo ".double" || :)
 
         echo "name=godot.${{ inputs.platform }}.${TARGET}${DOUBLE}.${{ inputs.arch }}.exe" >> $GITHUB_OUTPUT
+
+
+    # ---------------------- Publish generated artifacts --------------------- #
+
+    # Compiled export template
+    - uses: actions/upload-artifact@v4
+      with:
+        name: ${{ steps.export-template.outputs.name }}
+        path: ${{ steps.export-template.outputs.path }}
+        if-no-files-found: error
