feat(ci): build images if missing (#99)

diff --git a/.github/workflows/publish-image-godot-infra.yaml b/.github/workflows/publish-image-godot-infra.yaml
--- a/.github/workflows/publish-image-godot-infra.yaml
+++ b/.github/workflows/publish-image-godot-infra.yaml
@@ -16,20 +16,37 @@ env:
   # The Godot minor version which images on 'main' are defined to support. Only
   # one version of the image will be provided per Godot minor version/platform
   # pair.
-  GODOT_MAJOR_MINOR_VERSION: 4.3
+  GODOT_MAJOR_MINOR_VERSION: 4.2
 
 jobs:
-  changes:
+  build-required:
     runs-on: ubuntu-latest
     timeout-minutes: 4
 
     outputs:
-      compile-godot-export-template-macos: ${{ steps.compile-godot-export-template-macos.outputs.any_modified == 'true' }}
-      compile-godot-export-template-windows: ${{ steps.compile-godot-export-template-windows.outputs.any_modified == 'true' }}
-      export-godot-project-preset-macos: ${{ steps.export-godot-project-preset-macos.outputs.any_modified == 'true' }}
-      export-godot-project-preset-windows: ${{ steps.export-godot-project-preset-windows.outputs.any_modified == 'true' }}
+      version: ${{ steps.target.outputs.version }}
+      compile-godot-export-template-macos: ${{ steps.compile-godot-export-template-macos.outputs.any_modified == 'true' || steps.missing.outputs.compile-godot-export-template-macos == 'true' }}
+      compile-godot-export-template-windows: ${{ steps.compile-godot-export-template-windows.outputs.any_modified == 'true' || steps.missing.outputs.compile-godot-export-template-windows == 'true' }}
+      export-godot-project-preset-macos: ${{ steps.export-godot-project-preset-macos.outputs.any_modified == 'true' || steps.missing.outputs.export-godot-project-preset-macos == 'true' }}
+      export-godot-project-preset-windows: ${{ steps.export-godot-project-preset-windows.outputs.any_modified == 'true' || steps.missing.outputs.export-godot-project-preset-windows == 'true' }}
 
     steps:
+      - name: Determine the target major-minor version
+        id: target
+        shell: bash
+        run: |
+          VERSION="${{ env.GODOT_MAJOR_MINOR_VERSION }}"
+          if [[ "${{ github.ref_name }}" != "main" ]]; then
+            VERSION="$(echo ${{ github.ref_name }} | sed -E 's/^godot-//' | sed -E 's/^v//')"
+          fi
+
+          if [[ -z "$VERSION" ]]; then
+            echo "Failed to determine version!"
+            exit 1
+          fi
+
+          echo "version=$VERSION" >> $GITHUB_OUTPUT
+
       - uses: actions/checkout@v4
         with:
           fetch-depth: 2
@@ -58,74 +75,65 @@ jobs:
         with:
           files: export-godot-project-preset/windows/Dockerfile
 
-  godot-major-minor-version:
-    needs: ["changes"]
-    if: |
-      needs.changes.outputs.compile-godot-export-template-macos == 'true' ||
-      needs.changes.outputs.compile-godot-export-template-windows == 'true' ||
-      needs.changes.outputs.export-godot-project-preset-macos == 'true' ||
-      needs.changes.outputs.export-godot-project-preset-windows == 'true'
+      - name: Login to GitHub Container Registry
+        uses: docker/login-action@v3
+        with:
+          registry: ghcr.io
+          username: ${{ github.actor }}
+          password: ${{ github.token }}
 
-    runs-on: ubuntu-latest
-    timeout-minutes: 2
-
-    outputs:
-      value: ${{ steps.target.outputs.godot-major-minor-version }}
-
-    steps:
-      - name: Determine the target major-minor version
-        id: target
+      - name: Check for missing images
+        id: missing
         shell: bash
         run: |
-          VERSION="${{ env.GODOT_MAJOR_MINOR_VERSION }}"
-          if [[ "${{ github.ref_name }}" != "main" ]]; then
-            VERSION="$(echo ${{ github.ref_name }} | sed -E 's/^godot-//' | sed -E 's/^v//')"
-          fi
-
-          echo "godot-major-minor-version=$VERSION" >> $GITHUB_OUTPUT
+          for img in compile-godot-export-template export-godot-project-preset; do
+            for platform in macos windows; do
+              if [[ $(docker manifest inspect ghcr.io/coffeebeats/$img:godot-v${{ steps.target.outputs.version }}-$platform &>/dev/null; echo $?) -ne 0 ]]; then
+                echo "$img-$platform=true" >> $GITHUB_OUTPUT
+              fi
+            done
+          done
 
   compile-godot-export-template-macos:
-    needs: ["changes", "godot-major-minor-version"]
+    needs: ["build-required"]
 
-    if: needs.changes.outputs.compile-godot-export-template-macos == 'true'
+    if: needs.build-required.outputs.compile-godot-export-template-macos == 'true'
 
     uses: "./.github/workflows/publish-image-compile-godot-export-template-macos.yaml"
     with:
-      godot-major-minor-version: ${{ needs.godot-major-minor-version.outputs.value }}
+      godot-major-minor-version: ${{ needs.build-required.outputs.version }}
 
   compile-godot-export-template-windows:
-    needs: ["changes", "godot-major-minor-version"]
+    needs: ["build-required"]
 
-    if: needs.changes.outputs.compile-godot-export-template-windows == 'true'
+    if: needs.build-required.outputs.compile-godot-export-template-windows == 'true'
 
     uses: "./.github/workflows/publish-image-compile-godot-export-template-windows.yaml"
     with:
-      godot-major-minor-version: ${{ needs.godot-major-minor-version.outputs.value }}
+      godot-major-minor-version: ${{ needs.build-required.outputs.version }}
 
   export-godot-project-preset-macos:
     needs:
-      - "changes"
-      - "godot-major-minor-version"
+      - "build-required"
       # NOTE: Fake a concurrency limit of '2' by depending on the two 'compile-*' images.
       - "compile-godot-export-template-macos"
       - "compile-godot-export-template-windows"
 
-    if: needs.changes.outputs.export-godot-project-preset-macos == 'true'
+    if: needs.build-required.outputs.export-godot-project-preset-macos == 'true'
 
     uses: "./.github/workflows/publish-image-export-godot-project-preset-macos.yaml"
     with:
-      godot-major-minor-version: ${{ needs.godot-major-minor-version.outputs.value }}
+      godot-major-minor-version: ${{ needs.build-required.outputs.version }}
 
   export-godot-project-preset-windows:
     needs:
-      - "changes"
-      - "godot-major-minor-version"
+      - "build-required"
       # NOTE: Fake a concurrency limit of '2' by depending on the two 'compile-*' images.
       - "compile-godot-export-template-macos"
       - "compile-godot-export-template-windows"
 
-    if: needs.changes.outputs.export-godot-project-preset-windows == 'true'
+    if: needs.build-required.outputs.export-godot-project-preset-windows == 'true'
 
     uses: "./.github/workflows/publish-image-export-godot-project-preset-windows.yaml"
     with:
-      godot-major-minor-version: ${{ needs.godot-major-minor-version.outputs.value }}
+      godot-major-minor-version: ${{ needs.build-required.outputs.version }}
