fix(ci): don't fail on import error

diff --git a/.github/workflows/publish-addon-update.yaml b/.github/workflows/publish-addon-update.yaml
--- a/.github/workflows/publish-addon-update.yaml
+++ b/.github/workflows/publish-addon-update.yaml
@@ -93,7 +93,11 @@ jobs:
 
           # Reimport assets so *.import files are updated.
           if [[ -f "project.godot" ]]; then
-            godot --editor --headless --import --quit
+            # NOTE: It's okay if this fails, probably. For example, coffeebeats/gut
+            # at '24f97b756fcc6a82375ef24b44c84bb1ee781786' fails with Godot
+            # 'v4.3-stable', but after the relevant imports occur.
+
+            godot --editor --headless --import --quit || :
           fi
 
           if [[ ! -d "addons/$NAME" ]]; then
